DEFAULT_INPUT_FILEPATH = 'input.yaml'
DEFAULT_OUTPUT_FILEPATH = 'generated/output.csv'

FIELD_DATE = 'Date'
FIELD_DAY_START_TIME = 'Start Time'
FIELD_DAY_END_TIME = 'End Time'
FIELD_LUNCH_BREAK_START_TIME = 'Lunch Start Time'
FIELD_LUNCH_BREAK_END_TIME = 'Lunch End Time'
FIELD_DAY_HOURS_WORKED = 'Hours Worked'
FIELD_NOTE = 'Note'

DATE_FORMAT = '%Y-%m-%d'
DAYS_IN_YEAR = 365

CSV_HEADERS = [
    FIELD_DATE,
    FIELD_DAY_START_TIME,
    FIELD_DAY_END_TIME,
    FIELD_LUNCH_BREAK_START_TIME,
    FIELD_LUNCH_BREAK_END_TIME,
    FIELD_DAY_HOURS_WORKED,  
    FIELD_NOTE,
]